on:
  push:
    branches: [ nuget ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: ODataExampleGen/ODataExampleGen.csproj
        # NuGet package id, used for version detection & defaults to project name
        PACKAGE_NAME: ODataExampleGen
        # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
        VERSION_FILE_PATH: ODataExampleGen/ODataExampleGen.csproj
        # Flag to toggle git tagging, enabled by default
        TAG_COMMIT: true
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{secrets.NUGETKEY}}
        # NuGet server uri hosting the packages, defaults to https://api.nuget.org
        NUGET_SOURCE: https://api.nuget.org
        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        INCLUDE_SYMBOLS: true

